### PR TITLE
Skip some tests on gfx1151 APU that consume too much memory (#874)

### PR DESCRIPTION
**Pull request by jsandham**
Summary of proposed changes:
- Cherrypick https://github.com/ROCm/rocSPARSE/commit/33af5ae77e0247ae53efdb05de422c341e0b8ba2 in 6.3

### CODE REVIEW

**Review by YvanMokwinski — APPROVED** [review]

**Review by cgmb — COMMENTED** [review]
It would be nice to have a more systemic approach to handling hardware with differing amounts of memory.

This change fixes the immediate problem in the AMD testing environment, but it is not a scalable solution. The ISA does not dictate how much memory is available to the GPU, so the filter criteria only loosely correlates with the actual reason why the filtering is being done. It would be much better to directly query the amount of memory available and skip the tests that exceed that amount (and/or provide a way for the user to manually specify a memory limit, like via a command line option or an environment variable).

That's not something that needs to happen now. It's good to have a quick fix for the immediate problem. That's just my suggestion for the long term. In my spare time, I am personally testing on a broad range of APUs with differing amounts of memory available  (gfx902, gfx909, gfx90c, gfx1033, gfx1035, gfx1103) and there's no way I'm going to be able to make these sorts of changes for all of them.

**Comment by YvanMokwinski** [comment]
> It would be nice to have a more systemic approach to handling hardware with differing amounts of memory.
> 
> This change fixes the immediate problem in the AMD testing environment, but it is not a scalable solution. The ISA does not dictate how much memory is available to the GPU, so the filter criteria only loosely correlates with the actual reason why the filtering is being done. It would be much better to directly query the amount of memory available and skip the tests that exceed that amount (and/or provide a way for the user to manually specify a memory limit, like via a command line option or an environment variable).
> 
> That's not something that needs to happen now. It's good to have a quick fix for the immediate problem. That's just my suggestion for the long term. In my spare time, I am personally testing on a broad range of APUs with differing amounts of memory available (gfx902, gfx909, gfx90c, gfx1033, gfx1035, gfx1103), and there's no way I'm going to be able to make these sorts of changes for all of them.

What do you think your approach would be to skip the test? 
- having a pre-defined amount of memory for each test?
- aborting and skipping the tests if a memory allocation fails? (I don't like it)
- other suggestion?

**Comment by cgmb** [comment]
Not all libraries have this feature in their tests, but rocBLAS and rocFFT both have strategies for handling memory limits. I'm not sure precisely how they work, but I think [rocFFT is probably the more sophisticated of the two](https://github.com/ROCm/rocFFT/blob/32be5041e6d83151b78cc5f8a8b285612e7039e2/clients/tests/gtest_main.cpp). I'd suggest trying to follow the same strategy as one of those two libraries.

**Comment by cgmb** [comment]
That is to say that I don't know the best way to do things. I think it basically boils down to doing a memory query for whatever function is being tested, checking that value against the limit, and skipping the test if the reported memory required for the test is greater than the limit.

We haven't dealt with this in rocSOLVER, as all our tests have been on (relatively) small matrices until fairly recently. So, I don't have direct hands-on experience with any implementation.

**Pull request merged**
